galaxy_info:
  author: Brandon Marlow
  description: A role for automated management of Satellite lifecycle environments and content views
  company: Red Hat
  license: BSD-3-Clause

  min_ansible_version: "2.9"

  galaxy_tags:
    - satellite
    - katello
    - foreman
    - theforeman
    - update
    - content-view
    - lifecycle
    - patch
    - patching

collections:
  - theforeman.foreman