---
galaxy_info:
  author: Richard Stempfl
  description: Create users, usergroups, LDAP auth, and link int with ext group
  company: Atix
  license: GPL-3.0-only
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - Orcharhino
    - Foreman
    - Katello
    - Satelite
    - foreman-ansible-modules
dependencies: []
